[loggers]
keys=root,osken,IntelliFlowController

[handlers]
keys=console,file

[formatters]
keys=simple,detailed

[logger_root]
level=WARNING
handlers=console

[logger_osken]
level=WARNING
handlers=console
qualname=os_ken
propagate=0

[logger_IntelliFlowController]
level=INFO
handlers=console,file
qualname=IntelliFlowController
propagate=0

[handler_console]
class=StreamHandler
level=DEBUG
formatter=detailed
args=(sys.stdout,)

[handler_file]
class=FileHandler
level=DEBUG
formatter=detailed
args=('intelliflow.log', 'a')

[formatter_simple]
format=%(message)s

[formatter_detailed]
format=[%(asctime)s] %(message)s
datefmt=%H:%M:%S
